<?php

/**
 * Implements hook_permission().
 */
function emergency_block_permission() {
  $perms['control emergency block'] = [
    'title' => t('Enable or disable the emergency message'),
  ];

  return $perms;
}

/**
* Implements hook_menu_link_defaults().
*/
function emergency_block_menu_link_defaults() {
  $links['emergency_block.admin.status'] = array(
    'link_title' => 'Emergency status',
    'description' => 'Set the status of the emergency block.',
    'route_name' => 'emergency_block.status',
    'parent' => 'system.admin.config.system',
  );
  return $links;
}

/**
 * Implements hook_theme().
 */
function emergency_block_theme() {
  $theme['emergency_block'] = [
    'variables' => array('message' => NULL, 'reason' => NULL, 'link' => NULL),
    'template' => 'emergency_block',
  ];

  return $theme;
}
