<?php

/**
 * Implements hook_permission().
 */
function emergency_block_permission() {
  $perms['administer emergency weather settings'] = [
    'title' => t('Set weather settings for the emergency block'),
  ];
  $perms['control emergency block'] = [
    'title' => t('Enable or disable the emergency message'),
  ];

  return $perms;
}

/**
 * Implements hook_theme().
 */
function emergency_block_theme() {
  $theme['emergency_block'] = [
    'variables' => array('message' => NULL, 'reason' => NULL, 'link' => NULL),
    'template' => 'emergency_block',
  ];

  return $theme;
}

/**
 * Implements hook_cron().
 */
function emergency_block_cron() {
  \Drupal::service('emergency_block.weather')->updateTemperature();
}
