<?php

/**
 * Implements hook_permission().
 */
function violator_block_permission() {
  $perms['administer violator weather settings'] = [
    'title' => t('Set weather settings for the violator block'),
  ];
  $perms['control violator block'] = [
    'title' => t('Enable or disable the violator message'),
  ];

  return $perms;
}

/**
* Implements hook_menu_link_defaults().
*/
function violator_block_menu_link_defaults() {
  $links['violator_block.admin.status'] = array(
    'link_title' => 'Violator status',
    'description' => 'Set the status of the violator block.',
    'route_name' => 'violator_block.status',
    'parent' => 'system.admin.config.system',
  );
  $links['violator_block.admin.weather'] = array(
    'link_title' => 'Violator weather',
    'description' => 'Configure the violator block weather usage.',
    'route_name' => 'violator_block.weather',
    'parent' => 'system.admin.config.system',
  );
  return $links;
}

/**
 * Implements hook_theme().
 */
function violator_block_theme() {
  $theme['violator_block'] = [
    'variables' => array('message' => NULL, 'weather' => NULL, 'emergency_status' => NULL),
    'template' => 'violator_block',
  ];

  return $theme;
}

/**
 * Implements hook_cron().
 */
function violator_block_cron() {
  \Drupal::service('violator_block.weather')->updateTemperature();
}
