violator_block.weather:
  type: mapping
  label: 'Violator Block weather configuration'
  mapping:
    weather_station:
      type: string
      label: "The weather station name to check"
    threshold:
      type: integer
      label: 'The temperature in Farenheit below which to show the violator notice'
    message:
      type: string
      label: "The message to show when it's too cold out"
